
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public Tbitem Tbitem {get; }
    /// <summary>
    /// 多语言表
    /// </summary>
    public Tblocalization Tblocalization {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        Tbitem = new Tbitem(loader("tbitem"));
        Tblocalization = new Tblocalization(loader("tblocalization"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tbitem.ResolveRef(this);
        Tblocalization.ResolveRef(this);
    }
}

}
