
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class item : Luban.BeanBase
{
    public item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["name_ch"].IsString) { throw new SerializationException(); }  NameCh = _buf["name_ch"]; }
        { if(!_buf["pic"].IsString) { throw new SerializationException(); }  Pic = _buf["pic"]; }
    }

    public static item Deserializeitem(JSONNode _buf)
    {
        return new item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 中文名称
    /// </summary>
    public readonly string NameCh;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Pic;
   
    public const int __ID__ = 3242771;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "nameCh:" + NameCh + ","
        + "pic:" + Pic + ","
        + "}";
    }
}
}

