
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class localization : Luban.BeanBase
{
    public localization(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["zh_cn"].IsString) { throw new SerializationException(); }  ZhCn = _buf["zh_cn"]; }
        { if(!_buf["en"].IsString) { throw new SerializationException(); }  En = _buf["en"]; }
    }

    public static localization Deserializelocalization(JSONNode _buf)
    {
        return new localization(_buf);
    }

    /// <summary>
    /// 文本ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string ZhCn;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string En;
   
    public const int __ID__ = -812005735;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "zhCn:" + ZhCn + ","
        + "en:" + En + ","
        + "}";
    }
}
}

