
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 多语言表
/// </summary>
public partial class Tblocalization
{
    private readonly System.Collections.Generic.Dictionary<int, localization> _dataMap;
    private readonly System.Collections.Generic.List<localization> _dataList;
    
    public Tblocalization(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, localization>(count);
        _dataList = new System.Collections.Generic.List<localization>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            localization _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.localization.Deserializelocalization(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, localization> DataMap => _dataMap;
    public System.Collections.Generic.List<localization> DataList => _dataList;

    public localization GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public localization Get(int key) => _dataMap[key];
    public localization this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

